CREATE DATABASE QuanLyNhanVien3;
USE QuanLyNhanVien3;

CREATE TABLE NguoiDung (
    NguoiDungId INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
    Email VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL UNIQUE,
    MatKhau VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
    VaiTro VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
    NgayDangKy DATE NOT NULL
);

CREATE TABLE NhanVien (
    NhanVienId INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanVien VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL UNIQUE,
    HoTen VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi VARCHAR(255) CHARACTER SET utf8mb4,
    SoDienThoai VARCHAR(15)
);

CREATE TABLE CaLamViec (
    CaId INT AUTO_INCREMENT PRIMARY KEY,
    TenCa VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
    ThoiGianBatDau TIME NOT NULL,
    ThoiGianKetThuc TIME NOT NULL
);

CREATE TABLE LichLamViec (
    LichId INT AUTO_INCREMENT PRIMARY KEY,
    NhanVienId INT,
    CaId INT,
    Ngay DATE NOT NULL,
    UNIQUE (NhanVienId, CaId, Ngay),
    FOREIGN KEY (NhanVienId) REFERENCES NhanVien(NhanVienId) ON DELETE CASCADE,
    FOREIGN KEY (CaId) REFERENCES CaLamViec(CaId) ON DELETE CASCADE
);

CREATE TABLE DiemDanh (
    DiemDanhId INT AUTO_INCREMENT PRIMARY KEY,
    NhanVienId INT,
    Ngay DATE NOT NULL,
    CaId INT,
    TrangThai VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
    UNIQUE (NhanVienId, CaId, Ngay),
    FOREIGN KEY (NhanVienId) REFERENCES NhanVien(NhanVienId) ON DELETE CASCADE,
    FOREIGN KEY (CaId) REFERENCES CaLamViec(CaId) ON DELETE CASCADE
);

CREATE TABLE Luong (
    LuongId INT AUTO_INCREMENT PRIMARY KEY,
    NhanVienId INT,
    LuongCoBan DECIMAL(10,2) NOT NULL,
    PhuCap DECIMAL(10,2),
    KhauTru DECIMAL(10,2),
    TongLuong DECIMAL(10,2) GENERATED ALWAYS AS (LuongCoBan + IFNULL(PhuCap, 0) - IFNULL(KhauTru, 0)) STORED,
    Thang VARCHAR(7) NOT NULL, -- Tháng và năm: 'MM/YYYY'
    FOREIGN KEY (NhanVienId) REFERENCES NhanVien(NhanVienId) ON DELETE CASCADE
);

CREATE TABLE HieuSuat (
    HieuSuatId INT AUTO_INCREMENT PRIMARY KEY,
    NhanVienId INT,
    Thang VARCHAR(7) NOT NULL,
    DiemHieuSuat INT NOT NULL,
    NhanXet VARCHAR(255) CHARACTER SET utf8mb4,
    FOREIGN KEY (NhanVienId) REFERENCES NhanVien(NhanVienId) ON DELETE CASCADE
);
